- .gitignore
- src/App.vue
- src/components/httpObject.js
- src/components/interactive/ButtonControl.vue
- src/components/interactive/InteractiveMap.vue
- src/components/interactive/SensorHistoryChart.vue
- src/components/interactive/SensorMenu.vue
- src/components/interactive/Slider.vue
- src/components/interactive/SliderAdvanced.vue
- src/components/main/GlobalError.vue
- src/components/main/Sensor.vue
- src/components/main/SideBar.vue
- src/components/main/TabNav.vue
- src/components/static/AirPressure.vue
- src/components/static/Barometer.vue
- src/components/static/BatteryLevel.vue
- src/components/static/DateTime.vue
- src/components/static/DefaultSensor.vue
- src/components/static/Humidity.vue
- src/components/static/LineChart.vue
- src/components/static/Rain.vue
- src/components/static/SunLight.vue
- src/components/static/Thermometer.vue
- src/components/static/WaterLevel.vue
- src/components/static/chart-data.js
- src/pages/Dashboard/Dashboard.vue
- src/router/index.ts
- added the structure of  other components for future rework
> Added Dashboard

- src/components/httpObject.ts
- src/pages/Dashboard/Dashboard.vue
- src/pages/Login/Login.vue
- src/router/index.ts
- vite.config.ts
fixed HTTP object type and proxy
> Fixed login and redirect

- src/components/Sensor.vue
- src/components/interactive/ButtonControl.vue
- src/components/interactive/SensorHistoryChart.vue
- src/components/interactive/SensorMenu.vue
- src/components/sensors/AirPressure.vue
- src/components/sensors/Barometer.vue
- src/components/sensors/BatteryLevel.vue
- src/components/sensors/DateTime.vue
- src/components/sensors/DefaultSensor.vue
- src/components/sensors/Humidity.vue
- src/components/sensors/Rain.vue
- src/components/sensors/SunLight.vue
- src/components/sensors/Thermometer.vue
- src/components/sensors/WaterLevel.vue
- src/pages/SingleDevice/SingleDevice.vue
> Fixed console errs and warns

- src/components/TabNav.vue
- src/components/sensors/AirPressure.vue
- src/components/sensors/Barometer.vue
- src/components/sensors/BatteryLevel.vue
- src/components/sensors/DateTime.vue
- src/components/sensors/Humidity.vue
- src/components/sensors/Rain.vue
- src/components/sensors/SunLight.vue
- src/components/sensors/Thermometer.vue
- src/components/sensors/WaterLevel.vue
- src/pages/SingleDevice/SingleDevice.vue
small refactoring of "updateSensors"
> Fixed sensors values

- src/components/SideBar.vue
- src/components/alerts/LineAlert.vue
- src/interfaces/UserInterface.ts
- src/pages/Device/Device.vue
- src/pages/Login/Login.vue
- src/rest/RestClient.ts
- src/types/OIOTEResponseType.ts
- fixed RestClient loginRequest to handle return of response and error
- fixed user cookie creation to work with the new changes
- fixed token acquisition in Device
- Device api call will be fixed in new issue
- fixed auto hiding of the line error
> Fixed login function

- src/pages/Device/Device.vue
- src/pages/Login/Login.vue
- src/rest/RestClient.ts
- fixed username displayed incorrectly
- fixed unused import in Login
> Added restClient in Device

- src/pages/Device/Device.vue
- src/pages/SingleDevice/SingleDevice.vue
- src/rest/RestClient.ts
- refactored device sensors component to use RestClient
- fixed sensor list to be populated properly
- minor fixes on Device component
> Fixed device sensors fetching

- src/components/TabNav.vue
> fix: Title auto change fixed

- src/pages/SingleDevice/SingleDevice.vue
The prop cause sensors not to be loaded
Due to framework rule <router-link>can't pass object as route param
Closes #41
> flx: change of sensors page props

- package.json
- src/pages/Device/Device.vue
- Extract repeating code in Devices page, to be contained in a single method
Fixes #31
> refactor: Extract device fetch method

- src/pages/Device/Device.vue
Solve duplication by use of a single function for fetching devices
Fixes #48, #15
> refactor: code duplication in device page

- src/rest/RestClient.ts
Response error object have different values from the success response
Fixes #50
> fix: wrong error value in RestClient reject

- src/components/TabNav.vue
For better visibility
Resolves: #52
> refactor: change logo section background

- src/interfaces/DeviceInterface.ts
- src/pages/Device/Device.vue
- src/pages/DeviceList/DeviceList.vue
- src/stores/deviceStore.ts
To store a deviceList state, and to access it from other components
Resolves #56
> feat: add device store

- src/components/sensors/Thermometer.vue
Duplication of for loop
Change in the styling
Closes #60
> refactor: thermometer component

- src/components/Sensor.vue
- src/components/sensors/AirPressure.vue
Duplication of for loop
Change in the styling
New updateGauge() to calculate the value of the meter
onMounted and watchEffect are asynchronous methods, which caused
wrong init of the variables.   
The comparison for sensorTypeName in Sensor.vue, has wrong value to compare with 
Closes #62
> refactor: AirPressure component

- src/components/sensors/Humidity.vue
Duplication of for loop
Change in the styling
New updateGauge() to calculate the value of the meter onMounted and watchEffect are asynchronous methods
Closes #64
> refactor: humidity component

- src/components/Sensor.vue
- src/components/sensors/BatteryLevel.vue
Remove duplication of for loop
Changes on the styling
New key value to check for sensorTypeName
Closes #69
> refactor: batterylevel sensor component

- src/components/Sensor.vue
- src/components/sensors/DefaultSensor.vue
- src/pages/Device/Device.vue
Remove old CSS classes
Using the proper data variable
"default-data" property is just "data" now
New height for the "sensor__body" container
Closes #79
> refactor: DefaultSensor component

- src/components/Sensor.vue
- src/components/sensors/WaterLevel.vue
- Modifications on the drawing functions
- Clean duplication of for loops
- Implement tailwind classes
- Switch to "advanced" for sensorTypeName
Closes #81
> refactor: WaterLevel component

- src/components/Sensor.vue
- src/components/sensors/SunLight.vue
- src/components/sensors/WaterLevel.vue
- Modifications on the drawing functions
- Clean duplication of for loops
- Implement tailwind classes
- Switch to "advanced" for sensorTypeName
- Fix of default return value in WaterLevel, should  be at 0
Closes #83
> refactor: SunLight component

- src/components/sensors/DateTime.vue
- src/types/SensorDataType.ts
- Remove duplication of for loop
- Changes on the styling
- New value in SensorDataType for string values
Closes #88
> refactor: DateTime component

- src/components/Sensor.vue
- src/interfaces/SensorInterface.ts
- src/interfaces/SensorTypeInterface.ts
- src/pages/Device/Device.vue
- SensorTypeInterface for the sensorTypeId object, inside Sensor
- sensorList and infoBoxData now use the correct type
- function createHttpBody not  used in this component
- props.content has the correct type now
Closes #92
> feat: new interface for the Sensor element

- src/components/TabNav.vue
Place the text element in the center of the logo div
Closes #98
> refactor: text in the logo placeholder
